version: 0.0
os: linux
files:
   - source: server/server.js
     destination: /var/www/html
hooks:
   AfterInstall:
    - location: scripts/stop.sh
      runas: root
   ApplicationStart:
    - location: scripts/start.sh
      timeout: 3600